# Model arguments
model_name_or_path: /mnt/cache/luzimu/rlhf_math/models/MetaMath-Mistral-7B
torch_dtype: bfloat16

# Data training arguments
# For definitions, see: src/h4/training/config.py
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ message['content'] }}{% elif message['role'] == 'system' %}\n{{ '' }}{% elif message['role'] == 'assistant' %}\n{{ message['content'] }}{% endif %}{% endfor %}"
dataset_mixer:
  /mnt/cache/luzimu/MetaMath/data/gsm8k_math_dpo_1x1: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.1
do_eval: false
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: zephyr-7b-gemma-dpo
learning_rate: 1.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 2
save_steps: 100
optim: adamw_torch
output_dir: /mnt/cache/luzimu/rlhf_math/alignment-handbook/outs/MetaMath-Mistral-7B_dpo1x1
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
push_to_hub: false
report_to:
- tensorboard
- wandb
run_name: MetaMath-Mistral-7B
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
